name: Tweet Bot

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"
        
    - name: Install dependencies
      run: npm install
      
    - name: Debug environment variables
      run: |
        echo "Checking environment variables..."
        echo "OPENAI_API_KEY: ${OPENAI_API_KEY:0:10}..."
        echo "TWITTER_APP_KEY: ${TWITTER_APP_KEY:0:10}..."
        echo "TWITTER_APP_SECRET: ${TWITTER_APP_SECRET:0:10}..."
        echo "TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN:0:10}..."
        echo "TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET:0:10}..."
        echo "UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY:0:10}..."
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
        TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}

    - name: Run tweet bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
        TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      run: node main.js